@startuml
header Product State
footer Created by OD153
state "Start" as start
state "Browse Products" as browseProducts
state "Add to Cart" as addToCart
state "Proceed to Checkout" as checkout
state "Process Payment" as processPayment
state "Order Confirmed" as orderConfirmed
state "Payment Failed" as paymentFailed

start --> browseProducts
browseProducts --> addToCart
addToCart --> checkout
checkout --> processPayment
processPayment --> orderConfirmed : Success
processPayment --> paymentFailed : Failure
paymentFailed --> checkout
@enduml
