
@startuml
header User State
footer Created by OD153
state "Start" as start
state "Enter Registration Details" as enterDetails
state "Validate Details" as validateDetails
state "Create Account" as createAccount
state "Account Created" as accountCreated
state "Error: Invalid Details" as error

start --> enterDetails
enterDetails --> validateDetails
validateDetails --> createAccount : Valid
validateDetails --> error : Invalid
createAccount --> accountCreated
error --> enterDetails
@enduml
